#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]

//! Raw BTstack bindings generated by bindgen.

pub mod generated {
    include!("generated/libusb_main_bindings.rs");
}

pub use generated::*;
